from __future__ import annotations

from html import escape
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://www.sandiegopalmprotection.com"
MANIFEST = ROOT / "journal-data" / "journal_entries.json"
CONTENT_DIR = ROOT / "journal-data" / "articles"
JOURNAL_DIR = ROOT / "palm-journal"
INDEX_PATH = ROOT / "palm-journal-new.html"
SITEMAP_PATH = ROOT / "sitemap.xml"
GENERATED_NOTE = "Generated by scripts/build_journal.py from journal-data/journal_entries.json."
MODIFIED_DATE = "2026-07-11"


def read_entries() -> list[dict]:
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))
    seen_slugs = set()
    seen_anchors = set()
    errors = []
    for entry in entries:
        required = [
            "slug", "title", "date", "date_label", "location", "category", "excerpt",
            "primary_image", "primary_image_alt", "legacy_anchor", "status", "page",
        ]
        for key in required:
            if key not in entry or entry[key] in ("", None):
                errors.append(f"{entry.get('slug', '<unknown>')}: missing {key}")
        slug = entry.get("slug", "")
        anchor = entry.get("legacy_anchor", "")
        if slug in seen_slugs:
            errors.append(f"duplicate slug: {slug}")
        if anchor in seen_anchors:
            errors.append(f"duplicate legacy anchor: {anchor}")
        seen_slugs.add(slug)
        seen_anchors.add(anchor)
        if entry.get("status") == "draft":
            continue
        image_path = normalize_site_path(entry.get("primary_image", ""))
        if image_path and not (ROOT / image_path).exists():
            errors.append(f"{slug}: missing primary image {entry.get('primary_image')}")
        if entry.get("page"):
            content_path = CONTENT_DIR / f"{slug}.html"
            if not content_path.exists():
                errors.append(f"{slug}: missing article content snippet {content_path}")
    if errors:
        raise SystemExit("\n".join(errors))
    return entries


def normalize_site_path(path: str) -> str:
    return path.replace("../", "").replace("./", "").split("#", 1)[0]


def absolutize(path: str) -> str:
    clean = normalize_site_path(path)
    return f"{BASE_URL}/{clean}" if clean else BASE_URL


def article_href(entry: dict, from_root: bool = True) -> str:
    prefix = "./" if from_root else ""
    return f"{prefix}palm-journal/{entry['slug']}.html" if from_root else f"./{entry['slug']}.html"


def card_image_src(entry: dict) -> str:
    return entry.get("primary_image", "./journal-hero.jpg")



def display_meta(entry: dict) -> str:
    date_label = entry.get("date_label", "")
    location = entry.get("location", "")
    if location and location.lower() not in date_label.lower():
        return f"{date_label} | {location}"
    return date_label

def page_title(entry: dict) -> str:
    return f"{entry['title']} | SDPP Palm Journal"


def meta_description(entry: dict) -> str:
    text = entry.get("excerpt", "")
    if len(text) > 155:
        text = text[:152].rstrip() + "..."
    return text


def shared_head(title: str, description: str, canonical: str, og_image: str, extra_json_ld: str = "") -> str:
    return f'''  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>{escape(title)}</title>\n  <meta name="description" content="{escape(description)}">\n  <link rel="canonical" href="{escape(canonical)}">\n  <meta property="og:title" content="{escape(title)}">\n  <meta property="og:description" content="{escape(description)}">\n  <meta property="og:image" content="{escape(og_image)}">\n  <meta property="og:type" content="article">\n{extra_json_ld}'''


def styles(relative_root: str = "./") -> str:
    logo = f"{relative_root}logo.png"
    return f'''  <style>
    body {{ margin: 0; font-family: Arial, sans-serif; color: #202020; background: #f7f4ee; line-height: 1.62; }}
    header {{ background: #1f3b2c; color: #fff; padding: 18px 6vw; display: flex; align-items: center; justify-content: space-between; gap: 24px; flex-wrap: wrap; }}
    .brand {{ display: flex; align-items: center; gap: 14px; color: #fff; text-decoration: none; font-weight: 700; }}
    .brand img {{ width: 54px; height: 54px; object-fit: contain; }}
    nav {{ display: flex; gap: 14px; align-items: center; flex-wrap: wrap; }}
    nav a {{ color: #fff; text-decoration: none; font-size: 0.95rem; }}
    .nav-cta, .call {{ background: #d7b46a; color: #1f3b2c; padding: 10px 14px; border-radius: 4px; font-weight: 700; }}
    .hero {{ background: #efe7d8; padding: 56px 6vw 42px; }}
    .hero-inner, main, footer .inner {{ max-width: 1120px; margin: 0 auto; }}
    .eyebrow, .entry-label, .category-label {{ color: #6f5b2e; font-weight: 700; letter-spacing: .04em; text-transform: uppercase; font-size: .78rem; }}
    h1 {{ font-size: clamp(2rem, 5vw, 4.1rem); line-height: 1.05; margin: 14px 0; color: #1f3b2c; }}
    h2 {{ color: #1f3b2c; font-size: clamp(1.45rem, 3vw, 2.2rem); line-height: 1.15; }}
    h3 {{ color: #1f3b2c; }}
    .lede {{ font-size: 1.14rem; max-width: 760px; }}
    main {{ padding: 42px 6vw 68px; }}
    .journal-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 22px; }}
    .journal-card {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; overflow: hidden; display: flex; flex-direction: column; }}
    .journal-card img {{ width: 100%; aspect-ratio: 4 / 3; object-fit: cover; display: block; background: #e6decf; }}
    .journal-card-content {{ padding: 18px; display: flex; flex-direction: column; gap: 8px; flex: 1; }}
    .journal-card h2 {{ font-size: 1.18rem; margin: 0; }}
    .journal-card p {{ margin: 0; }}
    .date-location {{ color: #5f5a50; font-size: .94rem; }}
    .read-link, .cta-button {{ color: #1f3b2c; font-weight: 700; text-decoration: underline; text-underline-offset: 3px; }}
    .featured {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; padding: 22px; margin-bottom: 28px; display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(240px, .9fr); gap: 24px; align-items: center; }}
    .featured img {{ width: 100%; aspect-ratio: 4 / 3; object-fit: cover; border-radius: 4px; }}
    .article-shell {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; padding: clamp(20px, 4vw, 42px); }}
    .article-meta {{ color: #5f5a50; font-weight: 700; }}
    .entry-card {{ display: grid; gap: 24px; }}
    .entry-hero img, .entry-hero.side-by-side img, .gallery-grid img {{ width: 100%; border-radius: 4px; object-fit: cover; }}
    .entry-hero.side-by-side, .gallery-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }}
    .entry-hero img {{ max-height: 560px; }}
    .image-caption {{ color: #5f5a50; font-size: .94rem; }}
    .breadcrumb {{ margin-bottom: 24px; font-size: .94rem; }}
    .breadcrumb a {{ color: #1f3b2c; }}
    .related-links {{ display: flex; flex-wrap: wrap; gap: 12px; margin-top: 16px; }}
    .related-links a {{ background: #efe7d8; color: #1f3b2c; padding: 10px 12px; border-radius: 4px; text-decoration: none; font-weight: 700; }}
    .assessment-cta {{ background: #1f3b2c; color: #fff; padding: 28px; border-radius: 6px; margin-top: 34px; }}
    .assessment-cta h2 {{ color: #fff; }}
    .assessment-cta a {{ color: #fff; font-weight: 700; }}
    footer {{ background: #14271e; color: #fff; padding: 28px 6vw; }}
    footer a {{ color: #fff; }}
    @media (max-width: 760px) {{ .featured {{ grid-template-columns: 1fr; }} header {{ align-items: flex-start; }} }}
  </style>'''


def header(relative_root: str = "./") -> str:
    return f'''<header>
  <a class="brand" href="{relative_root}index.html">
    <img src="{relative_root}logo.png" alt="San Diego Palm Health & Protection Logo">
    <span>San Diego Palm Protection</span>
  </a>
  <nav aria-label="Primary navigation">
    <a href="{relative_root}index.html">Home</a>
    <a href="{relative_root}palm-care-escondido.html">Escondido</a>
    <a href="{relative_root}palm-stewardship-plans.html">Stewardship Plans</a>
    <a href="{relative_root}palm-journal-new.html">Palm Journal</a>
    <a class="call" href="tel:2624923135">&#9742; 262-492-3135</a>
    <a class="nav-cta" href="mailto:sandiegopalmprotection@gmail.com?subject=Request%20Palm%20Assessment">Request Assessment</a>
  </nav>
</header>'''


def footer(relative_root: str = "./") -> str:
    return f'''<footer>
  <div class="inner">
    <p><strong>San Diego Palm Protection</strong> documents, monitors, and supports preservation-focused care for mature palms across San Diego County.</p>
    <p><a href="{relative_root}index.html">Home</a> | <a href="{relative_root}palm-journal-new.html">Palm Journal</a> | <a href="{relative_root}palm-faq-san-diego.html">Palm FAQ</a></p>
  </div>
</footer>'''


def json_ld_index(entries: list[dict]) -> str:
    items = []
    for idx, entry in enumerate([e for e in entries if e.get("status") == "published" and e.get("page")], 1):
        items.append({"@type": "ListItem", "position": idx, "url": entry["canonical_url"], "name": entry["title"]})
    data = {"@context": "https://schema.org", "@type": "CollectionPage", "name": "SDPP Palm Journal", "url": f"{BASE_URL}/palm-journal-new.html", "mainEntity": {"@type": "ItemList", "itemListElement": items}}
    return f'  <script type="application/ld+json">\n{json.dumps(data, indent=2)}\n  </script>'


def json_ld_article(entry: dict) -> str:
    data = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": entry["title"],
        "description": meta_description(entry),
        "image": absolutize(entry["primary_image"]),
        "datePublished": entry["date"],
        "dateModified": entry.get("modified_date", MODIFIED_DATE),
        "author": {"@type": "Organization", "name": "San Diego Palm Protection"},
        "publisher": {"@type": "Organization", "name": "San Diego Palm Protection", "logo": {"@type": "ImageObject", "url": f"{BASE_URL}/logo.png"}},
        "mainEntityOfPage": entry["canonical_url"],
    }
    return f'  <script type="application/ld+json">\n{json.dumps(data, indent=2)}\n  </script>'


def render_index(entries: list[dict]) -> None:
    published = [e for e in entries if e.get("status") == "published"]
    featured = next(e for e in published if e["slug"] == "classic-old-escondido-canary-island-date-palm")
    cards = []
    for entry in published:
        img = card_image_src(entry)
        card_id = escape(entry["legacy_anchor"])
        if entry.get("page"):
            action = f'<a class="read-link" href="{article_href(entry)}">Read the field note</a>'
        else:
            action = '<span class="date-location">Legacy library reference; editorial review required before individual article migration.</span>'
        cards.append(f'''      <article class="journal-card" id="{card_id}" data-slug="{escape(entry['slug'])}" data-page="{str(entry.get('page')).lower()}">
        <img src="{escape(img)}" alt="{escape(entry['primary_image_alt'])}" loading="lazy" decoding="async">
        <div class="journal-card-content">
          <span class="category-label">{escape(entry['category'])}</span>
          <h2>{escape(entry['title'])}</h2>
          <p class="date-location">{escape(display_meta(entry))}</p>
          <p>{escape(entry['excerpt'])}</p>
          {action}
        </div>
      </article>''')
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{shared_head('SDPP Palm Journal | Field Notes and Palm Documentation', 'A library of San Diego Palm Protection field notes, mature palm documentation, SAPW observations, and preservation-focused Palm Journal entries.', f'{BASE_URL}/palm-journal-new.html', absolutize(featured['primary_image']), json_ld_index(entries))}
{styles('./')}
</head>
<body>
<!-- {GENERATED_NOTE} -->
{header('./')}
<section class="hero">
  <div class="hero-inner">
    <span class="eyebrow">Palm Journal Library</span>
    <h1>Field Notes on Mature Palms in San Diego County</h1>
    <p class="lede">A local library of documented palm observations, preservation notes, South American palm weevil documentation, and mature landscape records from San Diego Palm Protection.</p>
  </div>
</section>
<main>
  <section class="featured" aria-labelledby="featured-entry">
    <div>
      <span class="category-label">Featured Entry</span>
      <h2 id="featured-entry">{escape(featured['title'])}</h2>
      <p class="date-location">{escape(display_meta(featured))}</p>
      <p>{escape(featured['excerpt'])}</p>
      <a class="read-link" href="{article_href(featured)}">Read the field note</a>
    </div>
    <img src="{escape(featured['primary_image'])}" alt="{escape(featured['primary_image_alt'])}" loading="lazy" decoding="async">
  </section>

  <section aria-labelledby="journal-library">
    <h2 id="journal-library">Palm Journal Entries</h2>
    <div class="journal-grid">
{chr(10).join(cards)}
    </div>
  </section>

  <section class="assessment-cta" id="contact">
    <h2>Have a Mature Palm Concern?</h2>
    <p>Send a few clear photos and the palm location context. SDPP can help organize observations before care, monitoring, or preservation decisions.</p>
    <p><a href="mailto:sandiegopalmprotection@gmail.com?subject=Request%20Palm%20Assessment">Request a palm assessment</a> or call/text <a href="tel:2624923135">262-492-3135</a>.</p>
  </section>
</main>
{footer('./')}
</body>
</html>
'''
    INDEX_PATH.write_text(html, encoding="utf-8")


def render_article(entry: dict, entries_by_slug: dict[str, dict]) -> None:
    content = (CONTENT_DIR / f"{entry['slug']}.html").read_text(encoding="utf-8")
    related_links = []
    for slug in entry.get("related", []):
        related = entries_by_slug.get(slug)
        if related and related.get("page") and related.get("status") == "published":
            related_links.append(f'<a href="./{escape(related["slug"])}.html">{escape(related["title"])}</a>')
    if not related_links:
        related_links.append('<a href="../palm-journal-new.html">Return to the Palm Journal library</a>')
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{shared_head(page_title(entry), meta_description(entry), entry['canonical_url'], absolutize(entry['primary_image']), json_ld_article(entry))}
{styles('../')}
</head>
<body>
<!-- {GENERATED_NOTE} -->
{header('../')}
<section class="hero">
  <div class="hero-inner">
    <nav class="breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Home</a> / <a href="../palm-journal-new.html">Palm Journal</a> / {escape(entry['title'])}</nav>
    <span class="eyebrow">{escape(entry['category'])}</span>
    <h1>{escape(entry['title'])}</h1>
    <p class="article-meta">{escape(display_meta(entry))}</p>
    <p class="lede">{escape(entry['excerpt'])}</p>
  </div>
</section>
<main>
  <article class="article-shell" id="{escape(entry['legacy_anchor'])}">
{content}
    <section aria-labelledby="related-field-notes">
      <h2 id="related-field-notes">Related Field Notes</h2>
      <div class="related-links">
        {''.join(related_links)}
      </div>
    </section>
  </article>
  <section class="assessment-cta" id="contact">
    <h2>Need Help Reading Palm Changes?</h2>
    <p>SDPP reviews mature palm observations with a preservation-first approach and avoids unsupported diagnosis from a single public image.</p>
    <p><a href="mailto:sandiegopalmprotection@gmail.com?subject=Request%20Palm%20Assessment">Request a palm assessment</a> or call/text <a href="tel:2624923135">262-492-3135</a>.</p>
  </section>
</main>
{footer('../')}
</body>
</html>
'''
    (JOURNAL_DIR / f"{entry['slug']}.html").write_text(html, encoding="utf-8")


def update_sitemap(entries: list[dict]) -> None:
    existing = SITEMAP_PATH.read_text(encoding="utf-8")
    ns_match = re.search(r'<urlset[^>]*xmlns="([^"]+)"', existing)
    ns = ns_match.group(1) if ns_match else "http://www.sitemaps.org/schemas/sitemap/0.9"
    ET.register_namespace('', ns)
    tree = ET.parse(SITEMAP_PATH)
    root_el = tree.getroot()
    loc_tag = f"{{{ns}}}loc"
    url_tag = f"{{{ns}}}url"
    lastmod_tag = f"{{{ns}}}lastmod"
    changefreq_tag = f"{{{ns}}}changefreq"
    priority_tag = f"{{{ns}}}priority"
    existing_locs = {loc.text for loc in root_el.findall(f".//{loc_tag}")}
    for entry in entries:
        if not (entry.get("status") == "published" and entry.get("page")):
            continue
        loc = entry["canonical_url"]
        if loc in existing_locs:
            continue
        url = ET.SubElement(root_el, url_tag)
        ET.SubElement(url, loc_tag).text = loc
        ET.SubElement(url, lastmod_tag).text = entry.get("modified_date", MODIFIED_DATE)
        ET.SubElement(url, changefreq_tag).text = "monthly"
        ET.SubElement(url, priority_tag).text = "0.70"
    tree.write(SITEMAP_PATH, encoding="utf-8", xml_declaration=True)


def main() -> None:
    entries = read_entries()
    JOURNAL_DIR.mkdir(exist_ok=True)
    for old_page in JOURNAL_DIR.glob("*.html"):
        old_page.unlink()
    entries_by_slug = {entry["slug"]: entry for entry in entries}
    render_index(entries)
    for entry in entries:
        if entry.get("status") == "published" and entry.get("page"):
            render_article(entry, entries_by_slug)
    update_sitemap(entries)
    print(f"Generated Palm Journal library and {sum(1 for e in entries if e.get('page') and e.get('status') == 'published')} article pages.")


if __name__ == "__main__":
    main()
