from __future__ import annotations

from html import escape
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET

from site_components import header as global_header, footer as global_footer

ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://www.sandiegopalmprotection.com"
MANIFEST = ROOT / "journal-data" / "journal_entries.json"
CONTENT_DIR = ROOT / "journal-data" / "articles"
JOURNAL_DIR = ROOT / "palm-journal"
INDEX_PATH = ROOT / "palm-journal-new.html"
SITEMAP_PATH = ROOT / "sitemap.xml"
GENERATED_NOTE = "Generated by scripts/build_journal.py from journal-data/journal_entries.json."
MODIFIED_DATE = "2026-07-11"
DOCUMENTED_LOSS_DIR = JOURNAL_DIR / "documented-loss"
DOCUMENTED_LOSS_URL = f"{BASE_URL}/palm-journal/documented-loss/"
DOCUMENTED_LOSS_LASTMOD = "2026-07-13"


def read_entries() -> list[dict]:
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))
    seen_slugs = set()
    seen_anchors = set()
    errors = []
    for entry in entries:
        required = [
            "slug", "title", "date", "date_label", "location", "category", "excerpt",
            "primary_image", "primary_image_alt", "legacy_anchor", "status", "page",
        ]
        for key in required:
            if key not in entry or entry[key] in ("", None):
                errors.append(f"{entry.get('slug', '<unknown>')}: missing {key}")
        slug = entry.get("slug", "")
        anchor = entry.get("legacy_anchor", "")
        if slug in seen_slugs:
            errors.append(f"duplicate slug: {slug}")
        if anchor in seen_anchors:
            errors.append(f"duplicate legacy anchor: {anchor}")
        seen_slugs.add(slug)
        seen_anchors.add(anchor)
        if entry.get("status") == "draft":
            continue
        image_path = normalize_site_path(entry.get("primary_image", ""))
        if image_path and not (ROOT / image_path).exists():
            errors.append(f"{slug}: missing primary image {entry.get('primary_image')}")
        if entry.get("page"):
            content_path = CONTENT_DIR / f"{slug}.html"
            if not content_path.exists():
                errors.append(f"{slug}: missing article content snippet {content_path}")
    if errors:
        raise SystemExit("\n".join(errors))
    return entries


def normalize_site_path(path: str) -> str:
    return path.replace("../", "").replace("./", "").split("#", 1)[0]


def absolutize(path: str) -> str:
    clean = normalize_site_path(path)
    return f"{BASE_URL}/{clean}" if clean else BASE_URL


def article_href(entry: dict, from_root: bool = True) -> str:
    prefix = "./" if from_root else ""
    return f"{prefix}palm-journal/{entry['slug']}.html" if from_root else f"./{entry['slug']}.html"


def card_image_src(entry: dict) -> str:
    return entry.get("primary_image", "./journal-hero.jpg")



def display_meta(entry: dict) -> str:
    date_label = entry.get("date_label", "")
    location = entry.get("location", "")
    if location and location.lower() not in date_label.lower():
        return f"{date_label} | {location}"
    return date_label

def page_title(entry: dict) -> str:
    return f"{entry['title']} | SDPP Palm Journal"


def meta_description(entry: dict) -> str:
    text = entry.get("excerpt", "")
    if len(text) > 155:
        text = text[:152].rstrip() + "..."
    return text


def shared_head(title: str, description: str, canonical: str, og_image: str, extra_json_ld: str = "", og_type: str = "article") -> str:
    return f'''  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>{escape(title)}</title>\n  <meta name="description" content="{escape(description)}">\n  <link rel="canonical" href="{escape(canonical)}">\n  <meta property="og:title" content="{escape(title)}">\n  <meta property="og:description" content="{escape(description)}">\n  <meta property="og:image" content="{escape(og_image)}">\n  <meta property="og:type" content="{escape(og_type)}">\n{extra_json_ld}'''


def _legacy_styles_reference(relative_root: str = "./") -> str:
    return f'''  <link rel="icon" href="{relative_root}logo.png" type="image/png">
  <link rel="stylesheet" href="{relative_root}site-assets/site.css">
  <link rel="stylesheet" href="{relative_root}site-assets/credentials.css">
  <style>
    .hero {{ background: #efe7d8; padding: 56px 6vw 42px; }}
    .hero-inner, main, footer .inner {{ max-width: 1120px; margin: 0 auto; }}
    .eyebrow, .entry-label, .category-label {{ color: #6f5b2e; font-weight: 700; letter-spacing: .04em; text-transform: uppercase; font-size: .78rem; }}
    h1 {{ font-size: clamp(2rem, 5vw, 4.1rem); line-height: 1.05; margin: 14px 0; color: #1f3b2c; }}
    h2 {{ color: #1f3b2c; font-size: clamp(1.45rem, 3vw, 2.2rem); line-height: 1.15; }}
    h3 {{ color: #1f3b2c; }}
    .lede {{ font-size: 1.14rem; max-width: 760px; }}
    main {{ padding: 42px 6vw 68px; }}
    .journal-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 22px; }}
    .journal-card {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; overflow: hidden; display: flex; flex-direction: column; }}
    .journal-card img {{ width: 100%; aspect-ratio: 4 / 3; object-fit: cover; display: block; background: #e6decf; }}
    .journal-card-content {{ padding: 18px; display: flex; flex-direction: column; gap: 8px; flex: 1; }}
    .journal-card h2 {{ font-size: 1.18rem; margin: 0; }}
    .journal-card p {{ margin: 0; }}
    .date-location {{ color: #5f5a50; font-size: .94rem; }}
    .read-link, .cta-button {{ color: #1f3b2c; font-weight: 700; text-decoration: underline; text-underline-offset: 3px; }}
    .featured {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; padding: 22px; margin-bottom: 28px; display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(240px, .9fr); gap: 24px; align-items: center; }}
    .featured img {{ width: 100%; aspect-ratio: 4 / 3; object-fit: cover; border-radius: 4px; }}
    .article-shell {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; padding: clamp(20px, 4vw, 42px); }}
    .article-shell figure {{ margin: 24px 0; max-width: 100%; }}
    .article-shell figure img {{ display: block; width: 100%; max-width: 100%; height: auto; }}
    .video-feature {{ margin: 34px 0; padding: clamp(18px, 3vw, 28px); background: #f7f4ee; border: 1px solid #d9c9ac; border-radius: 6px; }}
    .video-feature h2 {{ margin-top: 0; }}
    .vertical-video-frame {{ width: min(100%, 380px); aspect-ratio: 9 / 16; margin: 22px auto 14px; background: #111; overflow: hidden; border-radius: 8px; }}
    .vertical-video-frame iframe {{ display: block; width: 100%; height: 100%; border: 0; }}
    .video-fallback {{ margin: 0; text-align: center; }}
    .video-fallback a {{ color: #1f3b2c; font-weight: 700; }}
    .editorial-section {{ background: #fff; border: 1px solid #d9c9ac; border-left: 6px solid #8c6b2f; border-radius: 6px; padding: clamp(20px, 4vw, 34px); margin: 0 0 30px; }}
    .editorial-section p {{ max-width: 820px; }}
    .loss-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 18px; margin-top: 20px; }}
    .loss-card {{ background: #fff; border: 1px solid #e2d8c6; border-radius: 6px; padding: 20px; }}
    .loss-card ul {{ margin: 10px 0 0; padding-left: 20px; }}
    .loss-record {{ margin-top: 24px; border-top: 3px solid #8c6b2f; padding-top: 24px; }}
    .loss-record-header {{ display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-bottom: 12px; }}
    .loss-record-header h3 {{ margin: 0; font-size: clamp(1.35rem, 2.4vw, 1.8rem); }}
    .loss-record img {{ width: 100%; height: auto; display: block; border-radius: 4px; }}
    .loss-record figure {{ margin: 0; }}
    .status-pill {{ display: inline-block; background: #efe7d8; color: #1f3b2c; padding: 6px 10px; border-radius: 999px; font-size: .82rem; font-weight: 700; margin-right: 8px; }}
    .empty-state {{ background: #efe7d8; border: 1px dashed #b69b65; border-radius: 6px; padding: 20px; margin-top: 22px; }}
    .article-meta {{ color: #5f5a50; font-weight: 700; }}
    .entry-card {{ display: grid; gap: 24px; }}
    .entry-card > *, .entry-content, .entry-hero, .entry-photo {{ min-width: 0; max-width: 100%; }}
    .entry-hero img, .entry-hero.side-by-side img, .gallery-grid img, .entry-photo-grid img {{ width: 100%; max-width: 100%; height: auto; display: block; border-radius: 4px; object-fit: cover; }}
    .entry-hero.side-by-side, .gallery-grid, .entry-photo-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }}
    .entry-hero img {{ max-height: 560px; }}
    .image-caption {{ color: #5f5a50; font-size: .94rem; }}
    .breadcrumb {{ margin-bottom: 24px; font-size: .94rem; }}
    .breadcrumb a {{ color: #1f3b2c; }}
    .related-links {{ display: flex; flex-wrap: wrap; gap: 12px; margin-top: 16px; }}
    .related-links a {{ background: #efe7d8; color: #1f3b2c; padding: 10px 12px; border-radius: 4px; text-decoration: none; font-weight: 700; }}
    .assessment-cta {{ background: #1f3b2c; color: #fff; padding: 28px; border-radius: 6px; margin-top: 34px; }}
    .assessment-cta h2 {{ color: #fff; }}
    .assessment-cta a {{ color: #fff; font-weight: 700; }}
    @media (max-width: 760px) {{ .featured {{ grid-template-columns: 1fr; }} }}
  </style>'''


def styles(relative_root: str = "./") -> str:
    return f'''  <link rel="icon" href="{relative_root}logo.png" type="image/png">
  <link rel="stylesheet" href="{relative_root}site-assets/site.css">
  <link rel="stylesheet" href="{relative_root}site-assets/credentials.css">
  <link rel="stylesheet" href="{relative_root}site-assets/journal.css">'''


def header(relative_root: str = "./") -> str:
    return global_header(relative_root)


def footer(relative_root: str = "./") -> str:
    return global_footer(relative_root)


def json_ld_index(entries: list[dict]) -> str:
    items = []
    for idx, entry in enumerate([e for e in entries if e.get("status") == "published" and e.get("page")], 1):
        items.append({"@type": "ListItem", "position": idx, "url": entry["canonical_url"], "name": entry["title"]})
    data = {"@context": "https://schema.org", "@type": "CollectionPage", "name": "SDPP Palm Journal", "url": f"{BASE_URL}/palm-journal-new.html", "mainEntity": {"@type": "ItemList", "itemListElement": items}}
    return f'  <script type="application/ld+json">\n{json.dumps(data, indent=2)}\n  </script>'


def json_ld_article(entry: dict) -> str:
    data = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": entry["title"],
        "description": meta_description(entry),
        "image": absolutize(entry["primary_image"]),
        "datePublished": entry["date"],
        "dateModified": entry.get("modified_date", MODIFIED_DATE),
        "author": {"@type": "Organization", "name": "San Diego Palm Protection"},
        "publisher": {"@type": "Organization", "name": "San Diego Palm Protection", "logo": {"@type": "ImageObject", "url": f"{BASE_URL}/logo.png"}},
        "mainEntityOfPage": entry["canonical_url"],
    }
    return f'  <script type="application/ld+json">\n{json.dumps(data, indent=2)}\n  </script>'


def json_ld_documented_loss() -> str:
    data = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": "Documented Loss",
        "url": DOCUMENTED_LOSS_URL,
        "description": "A Palm Journal section for confirmed records of significant palms that have died, declined beyond practical recovery, or been removed from San Diego landscapes.",
        "isPartOf": {
            "@type": "CollectionPage",
            "name": "SDPP Palm Journal",
            "url": f"{BASE_URL}/palm-journal-new.html",
        },
        "publisher": {
            "@type": "Organization",
            "name": "San Diego Palm Protection",
            "logo": {"@type": "ImageObject", "url": f"{BASE_URL}/logo.png"},
        },
    }
    return f'  <script type="application/ld+json">\n{json.dumps(data, indent=2)}\n  </script>'


def render_index(entries: list[dict]) -> None:
    published = [e for e in entries if e.get("status") == "published" and e.get("public", True) is not False]
    featured = next(e for e in published if e["slug"] == "classic-old-escondido-canary-island-date-palm")
    cards = []
    for entry in published:
        img = card_image_src(entry)
        card_id = escape(entry["legacy_anchor"])
        if entry.get("page"):
            action = f'<a class="read-link" href="{article_href(entry)}">Read the field note</a>'
        else:
            action = ''
        cards.append(f'''      <article class="journal-card" id="{card_id}" data-slug="{escape(entry['slug'])}" data-page="{str(entry.get('page')).lower()}">
        <img src="{escape(img)}" alt="{escape(entry['primary_image_alt'])}" loading="lazy" decoding="async">
        <div class="journal-card-content">
          <span class="category-label">{escape(entry['category'])}</span>
          <h2>{escape(entry['title'])}</h2>
          <p class="date-location">{escape(display_meta(entry))}</p>
          <p>{escape(entry['excerpt'])}</p>
          {action}
        </div>
      </article>''')
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{shared_head('SDPP Palm Journal | Field Notes and Palm Documentation', 'A library of San Diego Palm Protection field notes, mature palm documentation, SAPW observations, and preservation-focused Palm Journal entries.', f'{BASE_URL}/palm-journal-new.html', absolutize(featured['primary_image']), json_ld_index(entries))}
{styles('./')}
</head>
<body>
<!-- {GENERATED_NOTE} -->
{header('./')}
<section class="hero">
  <div class="hero-inner">
    <span class="eyebrow">Palm Journal Library</span>
    <h1>Field Notes on Mature Palms in San Diego County</h1>
    <p class="lede">A local library of documented palm observations, preservation notes, South American palm weevil documentation, and mature landscape records from San Diego Palm Protection. <a href="./report-a-palm.html">Share a palm observation or dated photograph.</a> Nothing is published automatically.</p>
  </div>
</section>
<main id="main">
  <section class="featured" aria-labelledby="featured-entry">
    <div>
      <span class="category-label">Featured Entry</span>
      <h2 id="featured-entry">{escape(featured['title'])}</h2>
      <p class="date-location">{escape(display_meta(featured))}</p>
      <p>{escape(featured['excerpt'])}</p>
      <a class="read-link" href="{article_href(featured)}">Read the field note</a>
    </div>
    <img src="{escape(featured['primary_image'])}" alt="{escape(featured['primary_image_alt'])}" loading="lazy" decoding="async">
  </section>

  <section class="editorial-section" aria-labelledby="documented-loss-section">
    <span class="category-label">Permanent Journal Section</span>
    <h2 id="documented-loss-section">Documented Loss</h2>
    <p>Before-and-after field records of significant palms that have died, declined beyond practical recovery, or been removed from San Diego landscapes.</p>
    <p>This section is reserved for confirmed outcomes. Palms still being watched remain ongoing field records until death, removal, or irreversible structural loss is documented.</p>
    <a class="read-link" href="./palm-journal/documented-loss/">View Documented Loss records</a>
  </section>

  <section class="editorial-section" aria-labelledby="urban-forest-documentation-resource">
    <span class="category-label">Urban Forest Documentation</span>
    <h2 id="urban-forest-documentation-resource">Old Escondido Palm Documentation for Urban-Forest Decisions</h2>
    <p>A limited owner/SDPP photographic record showing how stable palm IDs, dated images, visible-condition notes, and loss chronology can support urban-forest and multi-palm decisions.</p>
    <a class="read-link" href="./urban-forest-palm-documentation.html#old-escondido-documentation-method">Review the approved civic documentation resource</a>
  </section>

  <section aria-labelledby="journal-library">
    <h2 id="journal-library">Palm Journal Entries</h2>
    <div class="journal-grid">
{chr(10).join(cards)}
    </div>
  </section>

  <section class="assessment-cta" id="contact">
    <h2>Seen Something Worth Recording?</h2>
    <p>Share a palm observation or dated photograph for private review. Contributions may inform future field records, but they are never published automatically.</p>
    <p><a href="./report-a-palm.html">Report a palm</a> or <a href="./palm-records-monitoring-verification.html#request">request private help with your own palm</a>.</p>
  </section>
</main>
{footer('./')}
</body>
</html>
'''
    INDEX_PATH.write_text(html, encoding="utf-8")


def _render_legacy_documented_loss_page() -> None:
    DOCUMENTED_LOSS_DIR.mkdir(parents=True, exist_ok=True)
    title = "Documented Loss | SDPP Palm Journal"
    description = "Documented Loss records confirmed removals, deaths, and irreversible landscape changes involving significant palms in San Diego County."
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{shared_head(title, description, DOCUMENTED_LOSS_URL, f'{BASE_URL}/journal-overview.jpg', json_ld_documented_loss(), 'website')}
{styles('../../')}
</head>
<body>
<!-- {GENERATED_NOTE} -->
{header('../../')}
<section class="hero">
  <div class="hero-inner">
    <nav class="breadcrumb" aria-label="Breadcrumb"><a href="../../index.html">Home</a> / <a href="../../palm-journal-new.html">Palm Journal</a> / Documented Loss</nav>
    <span class="eyebrow">Palm Journal Section</span>
    <h1>Documented Loss</h1>
    <p class="lede">Mature palms define properties, corners, streets, and old neighborhoods. Then, sometimes, they are gone. Documented Loss records significant palms that have died, declined beyond practical recovery, or been removed, separating confirmed outcomes from observations and unknowns.</p>
  </div>
</section>
<main id="main">
  <section class="article-shell" aria-labelledby="what-qualifies">
    <h2 id="what-qualifies">What Qualifies</h2>
    <p>A palm is included here only when death, removal, or irreversible structural loss has been documented. Palms still under observation remain classified as ongoing field records until their outcome is known.</p>
    <p>This is not a general decline category. A removal can be documented even when its underlying cause is not. These records identify what is confirmed, what was observed, and what remains unknown.</p>

    <div class="loss-grid" aria-label="Documented Loss status types">
      <div class="loss-card">
        <span class="status-pill">Confirmed Loss</span>
        <h3>Documented outcome</h3>
        <p>Used when removal, death, or irreversible structural loss has been recorded through dates, photographs, public observation, or other reliable documentation.</p>
      </div>
      <div class="loss-card">
        <span class="status-pill">Ongoing Observation</span>
        <h3>Still being watched</h3>
        <p>Used when decline is visible but the outcome is not known. Ongoing records can later be cross-listed here if a confirmed loss is documented.</p>
      </div>
    </div>
  </section>

  <section class="article-shell" aria-labelledby="las-palmas-loss">
    <span class="category-label">First Documented Loss Record</span>
    <article class="loss-record">
      <div class="loss-record-header">
        <h2 id="las-palmas-loss">Las Palmas Canary Island Date Palm</h2>
        <span class="status-pill">Documented outcome: Removed</span>
      </div>
      <p><strong>The removal is documented. The cause has not been publicly confirmed.</strong></p>
      <p>SDPP first contacted the Rentesc email address used for Las Palmas property outreach in early June while documenting the development's mature palm landscape. On July 11, after photographing a conspicuous change in the central crown of one Canary Island date palm, SDPP sent seven updated photographs identifying the concern. No response was found from that address or the rentesc.com domain. The palm was subsequently documented as removed.</p>
      <p>The timing is notable. The reason for the timing is unknown. No cause of decline has been publicly confirmed.</p>
      <p>The removal is confirmed. The explanation is not. The inbox remained quiet. The landscape changed anyway.</p>

      <div class="entry-hero side-by-side">
        <figure>
          <img src="../../laspalmas-escondido-CIDP.jpg" alt="Las Palmas apartment property frontage in Old Escondido with a mature Canary Island date palm and property signage" loading="lazy" decoding="async">
          <figcaption class="image-caption">Las Palmas palm landscape before the documented removal. This establishes property frontage and mature palm context.</figcaption>
        </figure>
        <figure>
          <img src="../../2026-07-10-las-palmas-declining-palm-crown-context-01.jpg" alt="Declining palm at Las Palmas in Old Escondido showing crown context with brown central and lateral fronds" loading="lazy" decoding="async">
          <figcaption class="image-caption">Affected Canary Island date palm shown in crown context on July 10, 2026. This photograph documents visible change, not a diagnosis.</figcaption>
        </figure>
      </div>

      <div class="loss-grid">
        <div class="loss-card">
          <h3>Verified Outreach Chronology</h3>
          <ul>
            <li>June 5, 2026 - Initial palm-protection introduction. Subject: <em>Protect Your Palm Trees</em>.</li>
            <li>June 8, 2026 - Mature Canary Island date palm photograph sent. Subject: <em>Beautiful Canary Island Palms</em>.</li>
            <li>June 12, 2026 - Property-stewardship follow-up with two palm photographs. Subject: <em>Support your Property Value and Leasing Appeal</em>.</li>
            <li>July 10, 2026 - Latest crown change photographed.</li>
            <li>July 11, 2026 - Seven updated photographs and observations sent. Subject: <em>Visible Crown Change at Las Palmas - Updated Photos</em>.</li>
            <li>Removal documented - exact removal date not stated here because no dated final-condition photograph is included in this draft record.</li>
          </ul>
        </div>
        <div class="loss-card">
          <h3>Current Evidence Limitation</h3>
          <p>This page includes before and progression photographs. A final-condition or post-removal photograph is not included in this draft record yet.</p>
          <p>The removal is recorded as the outcome, but the visible image set on this page does not itself show the removed condition.</p>
        </div>
      </div>

      <div class="loss-grid">
        <div class="loss-card">
          <h3>Confirmed Facts</h3>
          <ul>
            <li>Location: Las Palmas apartment property, Old Escondido.</li>
            <li>Species documented: Canary Island date palm.</li>
            <li>Outcome now documented: removal.</li>
            <li>Publicly confirmed cause: none.</li>
          </ul>
        </div>
        <div class="loss-card">
          <h3>Field Observations</h3>
          <ul>
            <li>Central-crown decline was conspicuous in the July 10, 2026 photographs.</li>
            <li>Healthy-looking palms elsewhere on the property provided comparison context.</li>
            <li>The surrounding palm landscape gave the property a visible Old Escondido identity.</li>
          </ul>
        </div>
        <div class="loss-card">
          <h3>Unknowns</h3>
          <ul>
            <li>The cause of decline has not been publicly confirmed.</li>
            <li>The reason for the removal timing is unknown.</li>
            <li>This record does not establish a South American palm weevil diagnosis.</li>
          </ul>
        </div>
      </div>

      <div class="entry-photo-grid" style="margin-top: 20px;">
        <figure>
          <img src="../../2026-07-10-las-palmas-declining-palm-crown-browning-detail-02.jpg" alt="Declining palm crown at Las Palmas in Old Escondido showing browning fronds and remaining green canopy context" loading="lazy" decoding="async">
          <figcaption class="image-caption">Central-crown change photographed July 10, 2026. The image documents browning and remaining green canopy context, not confirmed cause.</figcaption>
        </figure>
        <figure>
          <img src="../../2026-07-10-las-palmas-declining-palm-central-frond-necrosis-detail-03.jpg" alt="Central crown fronds on a declining palm at Las Palmas in Old Escondido showing brown or necrotic new-growth detail" loading="lazy" decoding="async">
          <figcaption class="image-caption">Central-frond detail photographed July 10, 2026. This supports the crown-change chronology but does not establish a South American palm weevil diagnosis.</figcaption>
        </figure>
        <figure>
          <img src="../../las-palmas-old_escondido_tall-cidp.jpg" alt="Las Palmas mature Canary Island date palm landscape in Old Escondido with surrounding street and property context" loading="lazy" decoding="async">
          <figcaption class="image-caption">Broader Las Palmas streetscape context before removal, showing how mature palms shaped the visible property landscape.</figcaption>
        </figure>
      </div>
    </article>
  </section>

  <section class="article-shell" aria-labelledby="future-records">
    <h2 id="future-records">Future Records</h2>
    <p>Each future Documented Loss record should be built from specific field evidence, not assumption. When records are added, they can include:</p>
    <div class="loss-grid">
      <div class="loss-card">
        <h3>Record Basics</h3>
        <ul>
          <li>Place or landscape name</li>
          <li>Location</li>
          <li>Palm species</li>
          <li>Baseline or before date</li>
          <li>Removal or confirmed-loss date</li>
        </ul>
      </div>
      <div class="loss-card">
        <h3>Visual Timeline</h3>
        <ul>
          <li>Before photographs</li>
          <li>Progression photographs</li>
          <li>Final-condition or removal photographs</li>
          <li>Decline timeline</li>
        </ul>
      </div>
      <div class="loss-card">
        <h3>Field Notes</h3>
        <ul>
          <li>Confirmed facts</li>
          <li>Observations or suspected causes</li>
          <li>Why the loss mattered to the surrounding landscape</li>
          <li>Links to related ongoing field records</li>
        </ul>
      </div>
    </div>
    <div class="empty-state">
      <p><strong>A removal can be documented even when its underlying cause is not.</strong> These records identify what is confirmed, what was observed, and what remains unknown.</p>
    </div>
  </section>

  <section class="assessment-cta" aria-labelledby="return-journal">
    <h2 id="return-journal">Return to the Palm Journal</h2>
    <p>Documented Loss is one part of the broader Palm Journal: field notes, visible-condition records, preservation context, and neighborhood palm observations across San Diego County.</p>
    <p><a href="../../palm-journal-new.html">Back to the Palm Journal library</a></p>
  </section>
</main>
{footer('../../')}
</body>
</html>
'''
    (DOCUMENTED_LOSS_DIR / "index.html").write_text(html, encoding="utf-8")


def render_documented_loss_page() -> None:
    """Generate the Documented Loss index from canonical journal records."""
    DOCUMENTED_LOSS_DIR.mkdir(parents=True, exist_ok=True)
    entries = [e for e in read_entries() if e.get("status") == "published" and e.get("category") == "Documented Loss"]
    cards = "".join(
        f'''<article class="loss-record"><div class="loss-record-header"><h2>{escape(entry["title"])}</h2><span class="status-pill">Documented Loss</span></div><p>{escape(entry["excerpt"])}</p><p class="article-meta">{escape(display_meta(entry))}</p><p><a class="read-link" href="../{escape(entry["slug"])}.html">Read the complete documented record</a></p></article>'''
        for entry in entries
    ) or '<p class="empty-state">No Documented Loss records are currently published.</p>'
    title = "Documented Loss | SDPP Palm Journal"
    description = "Documented Loss records confirmed removals, deaths, and irreversible landscape changes involving significant palms in San Diego County."
    page = f'''<!DOCTYPE html><html lang="en"><head>
{shared_head(title, description, DOCUMENTED_LOSS_URL, f'{BASE_URL}/images/las-palmas/01-property-context-laspalmas-escondido-cidp.jpg', json_ld_documented_loss(), 'website')}
{styles('../../')}</head><body><!-- {GENERATED_NOTE} -->{header('../../')}
<section class="hero"><div class="hero-inner"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="../../index.html">Home</a> / <a href="../../palm-journal-new.html">Palm Journal</a> / Documented Loss</nav><span class="eyebrow">Palm Journal Section</span><h1>Documented Loss</h1><p class="lede">Confirmed palm removals and losses, presented with a clear boundary between documented observation and attribution.</p></div></section>
<main id="main"><section class="article-shell"><h2>Published records</h2>{cards}<aside class="related-links" aria-label="Related documentation"><a href="../../urban-forest-palm-documentation.html#old-escondido-documentation-method">Review the Old Escondido urban-forest documentation resource</a><a href="../../palm-journal-new.html">Return to the Palm Journal</a></aside></section></main>{footer('../../')}</body></html>'''
    (DOCUMENTED_LOSS_DIR / "index.html").write_text(page, encoding="utf-8")


def render_article(entry: dict, entries_by_slug: dict[str, dict]) -> None:
    content = (CONTENT_DIR / f"{entry['slug']}.html").read_text(encoding="utf-8")
    related_links = []
    for slug in entry.get("related", []):
        related = entries_by_slug.get(slug)
        if related and related.get("page") and related.get("status") == "published":
            related_links.append(f'<a href="./{escape(related["slug"])}.html">{escape(related["title"])}</a>')
    if not related_links:
        related_links.append('<a href="../palm-journal-new.html">Return to the Palm Journal library</a>')
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{shared_head(page_title(entry), meta_description(entry), entry['canonical_url'], absolutize(entry['primary_image']), json_ld_article(entry))}
{styles('../')}
</head>
<body>
<!-- {GENERATED_NOTE} -->
{header('../')}
<section class="hero">
  <div class="hero-inner">
    <nav class="breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Home</a> / <a href="../palm-journal-new.html">Palm Journal</a> / {escape(entry['title'])}</nav>
    <span class="eyebrow">{escape(entry['category'])}</span>
    <h1>{escape(entry['title'])}</h1>
    <p class="article-meta">{escape(display_meta(entry))}</p>
    <p class="lede">{escape(entry['excerpt'])}</p>
  </div>
</section>
<main id="main">
  <article class="article-shell" id="{escape(entry['legacy_anchor'])}">
{content}
    <section aria-labelledby="related-field-notes">
      <h2 id="related-field-notes">Related Field Notes</h2>
      <div class="related-links">
        {''.join(related_links)}
      </div>
    </section>
  </article>
  <section class="assessment-cta" id="contact">
    <h2>Seen something similar?</h2>
    <p><a href="../report-a-palm.html">Share a palm observation or dated photograph.</a> Submissions are reviewed privately and are not published automatically.</p>
    <p><a href="../palm-records-monitoring-verification.html#request">Schedule a palm assessment</a> or call/text <a href="tel:2624923135">262-492-3135</a>.</p>
  </section>
</main>
{footer('../')}
</body>
</html>
'''
    (JOURNAL_DIR / f"{entry['slug']}.html").write_text(html, encoding="utf-8")


def update_sitemap(entries: list[dict]) -> None:
    existing = SITEMAP_PATH.read_text(encoding="utf-8")
    ns_match = re.search(r'<urlset[^>]*xmlns="([^"]+)"', existing)
    ns = ns_match.group(1) if ns_match else "http://www.sitemaps.org/schemas/sitemap/0.9"
    ET.register_namespace('', ns)
    tree = ET.parse(SITEMAP_PATH)
    root_el = tree.getroot()
    loc_tag = f"{{{ns}}}loc"
    url_tag = f"{{{ns}}}url"
    lastmod_tag = f"{{{ns}}}lastmod"
    changefreq_tag = f"{{{ns}}}changefreq"
    priority_tag = f"{{{ns}}}priority"

    urls_by_loc = {}
    for url in root_el.findall(f".//{url_tag}"):
        loc_node = url.find(loc_tag)
        if loc_node is not None and loc_node.text:
            urls_by_loc[loc_node.text] = url

    documented_loss_url = urls_by_loc.get(DOCUMENTED_LOSS_URL)
    if documented_loss_url is None:
        documented_loss_url = ET.SubElement(root_el, url_tag)
        ET.SubElement(documented_loss_url, loc_tag).text = DOCUMENTED_LOSS_URL
    for tag, value in (
        (lastmod_tag, DOCUMENTED_LOSS_LASTMOD),
        (changefreq_tag, "monthly"),
        (priority_tag, "0.75"),
    ):
        node = documented_loss_url.find(tag)
        if node is None:
            node = ET.SubElement(documented_loss_url, tag)
        node.text = value

    existing_locs = set(urls_by_loc)
    existing_locs.add(DOCUMENTED_LOSS_URL)
    core_manifest = ROOT / "site-config" / "core_routes.json"
    if core_manifest.exists():
        for filename in json.loads(core_manifest.read_text(encoding="utf-8")):
            loc = f"{BASE_URL}/" if filename == "index.html" else f"{BASE_URL}/{filename}"
            if loc in existing_locs:
                continue
            url = ET.SubElement(root_el, url_tag)
            ET.SubElement(url, loc_tag).text = loc
            ET.SubElement(url, lastmod_tag).text = MODIFIED_DATE
            ET.SubElement(url, changefreq_tag).text = "monthly"
            ET.SubElement(url, priority_tag).text = "0.80"
            existing_locs.add(loc)
    for entry in entries:
        if not (entry.get("status") == "published" and entry.get("page")):
            continue
        loc = entry["canonical_url"]
        if loc in existing_locs:
            continue
        url = ET.SubElement(root_el, url_tag)
        ET.SubElement(url, loc_tag).text = loc
        ET.SubElement(url, lastmod_tag).text = entry.get("modified_date", MODIFIED_DATE)
        ET.SubElement(url, changefreq_tag).text = "monthly"
        ET.SubElement(url, priority_tag).text = "0.70"
    tree.write(SITEMAP_PATH, encoding="utf-8", xml_declaration=True)


def main() -> None:
    entries = read_entries()
    JOURNAL_DIR.mkdir(exist_ok=True)
    for old_page in JOURNAL_DIR.glob("*.html"):
        old_page.unlink()
    entries_by_slug = {entry["slug"]: entry for entry in entries}
    render_index(entries)
    for entry in entries:
        if entry.get("status") == "published" and entry.get("page"):
            render_article(entry, entries_by_slug)
    render_documented_loss_page()
    update_sitemap(entries)
    print(f"Generated Palm Journal library and {sum(1 for e in entries if e.get('page') and e.get('status') == 'published')} article pages.")


if __name__ == "__main__":
    main()
